/**
 * AUTO-GENERATED by `apps/docs/scripts/build-machine-specs.mjs`. Do not edit by hand.
 *
 * Lists the Layer 2 machines whose `toJSON()` snapshot is published at
 * `/machine-specs/<name>.json`. Used by the `/play/<slug>` route to render
 * a "State machine" link to the JSON + stately.ai/viz.
 */

export interface MachineSpecMeta {
  /** Bare machine name, e.g. `toggle`. Matches the JSON filename. */
  readonly name: string;
  /** Source package, e.g. `@kumiki/machines/toggle`. */
  readonly pkg: string;
  /** One-line blurb echoing the build-machine-specs entry. */
  readonly blurb: string;
  /** Top-level state names, in declaration order. */
  readonly states: readonly string[];
  /** Initial state. */
  readonly initial: string;
}

export const MACHINE_SPECS = {
  accordion: {
    name: 'accordion',
    pkg: '@kumiki/machines/accordion',
    blurb: 'Single- or multi-region disclosure (APG accordion).',
    states: ['idle'] as const,
    initial: 'idle',
  },
  calendar: {
    name: 'calendar',
    pkg: '@kumiki/machines/calendar',
    blurb:
      'Date-grid focus & selection (Gregorian here, Hijri / Buddhist / Hebrew supported via @internationalized/date).',
    states: ['idle', 'disabled'] as const,
    initial: 'idle',
  },
  checkbox: {
    name: 'checkbox',
    pkg: '@kumiki/machines/checkbox',
    blurb: 'Tri-state (unchecked / checked / mixed) checkbox.',
    states: ['unchecked', 'checked', 'mixed', 'disabled'] as const,
    initial: 'unchecked',
  },
  combobox: {
    name: 'combobox',
    pkg: '@kumiki/machines/combobox',
    blurb: 'APG combobox (single-select listbox + filterable input).',
    states: ['idle', 'open', 'disabled'] as const,
    initial: 'idle',
  },
  dialog: {
    name: 'dialog',
    pkg: '@kumiki/machines/dialog',
    blurb: 'Modal / non-modal dialog with focus trap + scroll-lock states.',
    states: ['closed', 'open'] as const,
    initial: 'closed',
  },
  'form-field': {
    name: 'form-field',
    pkg: '@kumiki/machines/form-field',
    blurb: 'Per-field state (pristine / dirty / touched / validating / invalid).',
    states: ['pristine', 'editing', 'validating', 'valid', 'invalid'] as const,
    initial: 'pristine',
  },
  menu: {
    name: 'menu',
    pkg: '@kumiki/machines/menu',
    blurb: 'APG menu / menubar (open + highlighted item navigation).',
    states: ['closed', 'open'] as const,
    initial: 'closed',
  },
  'number-field': {
    name: 'number-field',
    pkg: '@kumiki/machines/number-field',
    blurb: 'APG spinbutton — bounded numeric input with step & long-press repeat.',
    states: ['idle', 'disabled'] as const,
    initial: 'idle',
  },
  popover: {
    name: 'popover',
    pkg: '@kumiki/machines/popover',
    blurb: 'Non-modal anchored panel.',
    states: ['closed', 'open'] as const,
    initial: 'closed',
  },
  'radio-group': {
    name: 'radio-group',
    pkg: '@kumiki/machines/radio-group',
    blurb: 'APG radiogroup with roving tabindex.',
    states: ['idle', 'disabled'] as const,
    initial: 'idle',
  },
  select: {
    name: 'select',
    pkg: '@kumiki/machines/select',
    blurb: 'APG listbox-style select (no inline filter — use combobox for that).',
    states: ['closed', 'open'] as const,
    initial: 'closed',
  },
  slider: {
    name: 'slider',
    pkg: '@kumiki/machines/slider',
    blurb: 'APG slider (single-thumb here; range slider composes two).',
    states: ['idle', 'disabled'] as const,
    initial: 'idle',
  },
  switch: {
    name: 'switch',
    pkg: '@kumiki/machines/switch',
    blurb: 'On/off switch (aria-checked).',
    states: ['off', 'on', 'disabled'] as const,
    initial: 'off',
  },
  tabs: {
    name: 'tabs',
    pkg: '@kumiki/machines/tabs',
    blurb: 'APG tabs — automatic / manual activation, RTL-aware arrow keys.',
    states: ['idle', 'disabled'] as const,
    initial: 'idle',
  },
  toast: {
    name: 'toast',
    pkg: '@kumiki/machines/toast',
    blurb: 'Live-region notification queue.',
    states: ['idle'] as const,
    initial: 'idle',
  },
  toggle: {
    name: 'toggle',
    pkg: '@kumiki/machines/toggle',
    blurb: 'aria-pressed two-state toggle.',
    states: ['unpressed', 'pressed', 'disabled'] as const,
    initial: 'unpressed',
  },
  tooltip: {
    name: 'tooltip',
    pkg: '@kumiki/machines/tooltip',
    blurb: 'Hover / focus tooltip with open-delay + group sharing.',
    states: ['closed', 'open'] as const,
    initial: 'closed',
  },
} as const satisfies Record<string, MachineSpecMeta>;

export type MachineSpecName = keyof typeof MACHINE_SPECS;

/**
 * Resolve a play-route slug (`machine-toggle`, `attachment-toggle`,
 * `component-toggle`) to its machine spec metadata if one exists.
 */
export function findMachineSpec(slug: string): MachineSpecMeta | undefined {
  const key = slug.replace(/^(machine|attachment|component)-/, '');
  return (MACHINE_SPECS as Record<string, MachineSpecMeta>)[key];
}
