/**
 * Registry of every Kumiki package available in the Playground.
 *
 * Generated by hand for now; future tooling can derive this from
 * `pnpm-workspace.yaml`. Each entry has:
 *   - `slug`: URL slug for `/play/<slug>`
 *   - `name`: full npm package name
 *   - `layer`: 0–5 (matches docs/design/02-architecture.md)
 *   - `summary`: one-line description
 *   - `live`: whether the package has a live, interactive demo (Layer 4/5 only)
 *   - `apgUrl`: matching APG pattern URL, if any
 *
 * The slug omits the `@kumiki/` prefix — `@kumiki/components/toggle` → `component-toggle`.
 */

import type { Component } from 'svelte';

export interface PlaygroundEntry {
  slug: string;
  name: string;
  layer: 0 | 1 | 2 | 3 | 4 | 5;
  summary: string;
  /** True when an interactive demo Svelte component is provided. */
  live: boolean;
  apgUrl?: string;
  /** Status hint for the UI badge. */
  status: 'unreleased' | 'preview' | 'stable';
}

export const PLAYGROUNDS: ReadonlyArray<PlaygroundEntry> = [
  // ── Shared / Layer 0–2 ───────────────────────────────────────────────────
  {
    slug: 'types',
    name: '@kumiki/types',
    layer: 0,
    summary: 'Shared TypeScript types — Snippet helpers, ARIA props, validation result types.',
    live: false,
    status: 'unreleased',
  },
  {
    slug: 'primitives',
    name: '@kumiki/primitives',
    layer: 1,
    summary:
      'Layer 1 framework-agnostic primitives — focus-trap, dismissable, id, locale, live-region, collection, interactions, motion, portal.',
    live: false,
    status: 'preview',
  },
  {
    slug: 'locale',
    name: '@kumiki/locale',
    layer: 1,
    summary: 'Per-language locale data, dynamically importable. Initial set: 10 languages.',
    live: false,
    status: 'unreleased',
  },
  {
    slug: 'runtime',
    name: '@kumiki/runtime',
    layer: 2,
    summary:
      'Minimal FSM runtime — pure TypeScript, framework-agnostic, with XState-compatible JSON export.',
    live: false,
    status: 'preview',
  },

  // ── Layer 2 — Machines ────────────────────────────────────────────────────
  {
    slug: 'machine-toggle',
    name: '@kumiki/machines/toggle',
    layer: 2,
    summary: 'Pure-TS FSM for the Toggle component.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/button/',
    status: 'preview',
  },
  {
    slug: 'machine-switch',
    name: '@kumiki/machines/switch',
    layer: 2,
    summary: 'Pure-TS FSM for the Switch component (on/off setting).',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/switch/',
    status: 'preview',
  },
  {
    slug: 'machine-combobox',
    name: '@kumiki/machines/combobox',
    layer: 2,
    summary:
      'Pure-TS FSM for Combobox: keyboard nav, async race-token guarding, generic over option type T.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/combobox/',
    status: 'preview',
  },
  {
    slug: 'machine-checkbox',
    name: '@kumiki/machines/checkbox',
    layer: 2,
    summary: 'Pure-TS tri-state FSM (unchecked / checked / mixed) for the Checkbox component.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/',
    status: 'preview',
  },
  {
    slug: 'machine-radio-group',
    name: '@kumiki/machines/radio-group',
    layer: 2,
    summary: 'Pure-TS FSM for RadioGroup with roving-tabindex select-on-focus.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/radio/',
    status: 'preview',
  },
  {
    slug: 'machine-tabs',
    name: '@kumiki/machines/tabs',
    layer: 2,
    summary: 'Pure-TS FSM for Tabs with manual + automatic activation modes.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/tabs/',
    status: 'preview',
  },
  {
    slug: 'machine-dialog',
    name: '@kumiki/machines/dialog',
    layer: 2,
    summary: 'Pure-TS FSM for Dialog with policy-driven Escape / outside-click dismissal.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/',
    status: 'preview',
  },
  {
    slug: 'machine-tooltip',
    name: '@kumiki/machines/tooltip',
    layer: 2,
    summary: 'Pure-TS FSM for Tooltip with configurable open / close delays.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/',
    status: 'preview',
  },
  {
    slug: 'machine-select',
    name: '@kumiki/machines/select',
    layer: 2,
    summary: 'Pure-TS FSM for Select — listbox without free-text input, with type-ahead.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/listbox/',
    status: 'preview',
  },
  {
    slug: 'machine-form-field',
    name: '@kumiki/machines/form-field',
    layer: 2,
    summary:
      'Pure-TS FSM for Form Field validation — pristine/editing/validating/valid/invalid with race-token guarding.',
    live: false,
    status: 'preview',
  },
  {
    slug: 'machine-accordion',
    name: '@kumiki/machines/accordion',
    layer: 2,
    summary: 'Pure-TS FSM for Accordion — single / multiple expansion modes with focus navigation.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/accordion/',
    status: 'preview',
  },
  {
    slug: 'machine-slider',
    name: '@kumiki/machines/slider',
    layer: 2,
    summary: 'Pure-TS FSM for Slider — clamped numeric value with step + pageStep increments.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/slider/',
    status: 'preview',
  },
  {
    slug: 'machine-number-field',
    name: '@kumiki/machines/number-field',
    layer: 2,
    summary:
      'Pure-TS FSM for NumberField — nullable numeric value with clamp + snap + page-step semantics.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/spinbutton/',
    status: 'preview',
  },
  {
    slug: 'machine-popover',
    name: '@kumiki/machines/popover',
    layer: 2,
    summary:
      'Pure-TS FSM for Popover — non-modal disclosure with closeOnEscape / closeOnOutsideClick policy flags.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/dialog/',
    status: 'preview',
  },
  {
    slug: 'machine-toast',
    name: '@kumiki/machines/toast',
    layer: 2,
    summary:
      'Pure-TS FSM for Toast (toaster queue) — ADD/REMOVE/UPDATE/CLEAR with max-size trim, politeness, sticky vs auto-dismiss.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/alert/',
    status: 'preview',
  },
  {
    slug: 'machine-menu',
    name: '@kumiki/machines/menu',
    layer: 2,
    summary:
      'Pure-TS FSM for Menu (single-level) — open/close + active-descendant cursor + arrow / Home / End / typeahead. Submenus deferred.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/menubar/',
    status: 'preview',
  },

  // ── Layer 3 — Attachments ────────────────────────────────────────────────
  {
    slug: 'attachment-toggle',
    name: '@kumiki/headless/toggle',
    layer: 3,
    summary: 'Svelte 5 attachment for Toggle. Drives ARIA + data-state directly on a DOM node.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/button/',
    status: 'preview',
  },
  {
    slug: 'attachment-switch',
    name: '@kumiki/headless/switch',
    layer: 3,
    summary: 'Svelte 5 attachment for Switch. Drives role="switch" + aria-checked + data-state.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/switch/',
    status: 'preview',
  },
  {
    slug: 'attachment-combobox',
    name: '@kumiki/headless/combobox',
    layer: 3,
    summary:
      'Svelte 5 attachments for Combobox — input, listbox, option, trigger. Compound primitive across multiple DOM elements.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/combobox/',
    status: 'preview',
  },
  {
    slug: 'attachment-checkbox',
    name: '@kumiki/headless/checkbox',
    layer: 3,
    summary: 'Svelte 5 attachment for Checkbox. Tri-state aria-checked (true/false/mixed).',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/',
    status: 'preview',
  },
  {
    slug: 'attachment-radio-group',
    name: '@kumiki/headless/radio-group',
    layer: 3,
    summary:
      'Svelte 5 attachments for RadioGroup — group + per-item factories with roving tabindex.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/radio/',
    status: 'preview',
  },
  {
    slug: 'attachment-tabs',
    name: '@kumiki/headless/tabs',
    layer: 3,
    summary:
      'Svelte 5 attachments for Tabs — list / tab / panel factories with orientation + RTL keyboard handling.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/tabs/',
    status: 'preview',
  },
  {
    slug: 'attachment-dialog',
    name: '@kumiki/headless/dialog',
    layer: 3,
    summary:
      'Svelte 5 attachments for Dialog — trigger / content / overlay / close + focus-trap + dismissable + sibling inert.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/',
    status: 'preview',
  },
  {
    slug: 'attachment-tooltip',
    name: '@kumiki/headless/tooltip',
    layer: 3,
    summary:
      'Svelte 5 attachments for Tooltip — debounced timers, prefers-reduced-motion, hoverable content.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/',
    status: 'preview',
  },
  {
    slug: 'attachment-select',
    name: '@kumiki/headless/select',
    layer: 3,
    summary:
      'Svelte 5 attachments for Select — trigger / listbox / option compound with active-descendant + typeahead.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/listbox/',
    status: 'preview',
  },
  {
    slug: 'attachment-form-field',
    name: '@kumiki/headless/form-field',
    layer: 3,
    summary:
      'Svelte 5 attachments for Form Field — Standard Schema validator runner with race-token dispatch + ARIA wiring.',
    live: false,
    status: 'preview',
  },
  {
    slug: 'attachment-accordion',
    name: '@kumiki/headless/accordion',
    layer: 3,
    summary:
      'Svelte 5 attachments for Accordion — root / item / trigger / panel compound primitive with roving-tabindex nav.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/accordion/',
    status: 'preview',
  },
  {
    slug: 'attachment-slider',
    name: '@kumiki/headless/slider',
    layer: 3,
    summary:
      'Svelte 5 attachments for Slider — root + thumb factories with keyboard, pointer-drag, and RTL inversion.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/slider/',
    status: 'preview',
  },
  {
    slug: 'attachment-number-field',
    name: '@kumiki/headless/number-field',
    layer: 3,
    summary:
      'Svelte 5 attachments for NumberField — root / input / increment / decrement with spinbutton ARIA + format/parse hooks.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/spinbutton/',
    status: 'preview',
  },
  {
    slug: 'attachment-popover',
    name: '@kumiki/headless/popover',
    layer: 3,
    summary:
      'Svelte 5 attachments for Popover — trigger / content / close / title / description with dismissable + focus-on-open wiring.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/dialog/',
    status: 'preview',
  },
  {
    slug: 'attachment-toast',
    name: '@kumiki/headless/toast',
    layer: 3,
    summary:
      'Svelte 5 attachments for Toast — viewport / item / closeButton with auto-dismiss, hover-pause, and aria-live wiring.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/alert/',
    status: 'preview',
  },
  {
    slug: 'attachment-menu',
    name: '@kumiki/headless/menu',
    layer: 3,
    summary:
      'Svelte 5 attachments for Menu — trigger / menu / item compound with APG keyboard handling, dismissable wiring, activatedId-driven onSelect.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/menubar/',
    status: 'preview',
  },

  // ── Layer 4 — Compound components ────────────────────────────────────────
  {
    slug: 'component-toggle',
    name: '@kumiki/components/toggle',
    layer: 4,
    summary:
      'Compound `<Toggle.Root>` button — controlled or uncontrolled, with `child` snippet support.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/button/',
    status: 'preview',
  },
  {
    slug: 'component-switch',
    name: '@kumiki/components/switch',
    layer: 4,
    summary: 'Compound `<Switch.Root>` for an on/off setting (role="switch", aria-checked).',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/switch/',
    status: 'preview',
  },
  {
    slug: 'component-combobox',
    name: '@kumiki/components/combobox',
    layer: 4,
    summary:
      'Compound Combobox — Root / Input / Listbox / Item / Trigger. Generic over option type T.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/combobox/',
    status: 'preview',
  },
  {
    slug: 'component-checkbox',
    name: '@kumiki/components/checkbox',
    layer: 4,
    summary:
      'Compound `<Checkbox.Root>` for tri-state form checkboxes (role=checkbox, aria-checked).',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/',
    status: 'preview',
  },
  {
    slug: 'component-radio-group',
    name: '@kumiki/components/radio-group',
    layer: 4,
    summary: 'Compound `<Root>` + `<Item>` for mutually-exclusive option groups.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/radio/',
    status: 'preview',
  },
  {
    slug: 'component-tabs',
    name: '@kumiki/components/tabs',
    layer: 4,
    summary:
      'Compound `<Root>` / `<List>` / `<Tab>` / `<Panel>` for tabbed interfaces with manual + automatic activation.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/tabs/',
    status: 'preview',
  },
  {
    slug: 'component-dialog',
    name: '@kumiki/components/dialog',
    layer: 4,
    summary:
      'Compound `<Root>` / `<Trigger>` / `<Overlay>` / `<Content>` / `<Title>` / `<Description>` / `<Close>` for modal and non-modal dialogs.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/',
    status: 'preview',
  },
  {
    slug: 'component-tooltip',
    name: '@kumiki/components/tooltip',
    layer: 4,
    summary:
      'Compound `<Root>` / `<Trigger>` / `<Content>` for hover/focus tooltips with debounced delays.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/',
    status: 'preview',
  },
  {
    slug: 'component-select',
    name: '@kumiki/components/select',
    layer: 4,
    summary:
      'Compound `<Root>` / `<Trigger>` / `<Listbox>` / `<Option>` for picking one of N options. Generic over option value V.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/listbox/',
    status: 'preview',
  },
  {
    slug: 'component-form-field',
    name: '@kumiki/components/form-field',
    layer: 4,
    summary:
      'Compound `<Root>` / `<Label>` / `<Input>` / `<Errors>` / `<Description>` for accessible form fields with Standard Schema validation.',
    live: true,
    status: 'preview',
  },
  {
    slug: 'component-accordion',
    name: '@kumiki/components/accordion',
    layer: 4,
    summary:
      'Compound `<Root>` / `<Item>` / `<Trigger>` / `<Panel>` for stacked disclosure regions. Generic over item value V; single or multiple expansion modes.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/accordion/',
    status: 'preview',
  },
  {
    slug: 'component-slider',
    name: '@kumiki/components/slider',
    layer: 4,
    summary:
      'Compound `<Root>` / `<Thumb>` for continuous numeric input with step + pageStep, horizontal/vertical, RTL inversion.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/slider/',
    status: 'preview',
  },
  {
    slug: 'component-number-field',
    name: '@kumiki/components/number-field',
    layer: 4,
    summary:
      'Compound `<Root>` / `<Input>` / `<Increment>` / `<Decrement>` for precise numeric input with format/parse hooks and boundary-aware step buttons.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/spinbutton/',
    status: 'preview',
  },
  {
    slug: 'component-popover',
    name: '@kumiki/components/popover',
    layer: 4,
    summary:
      'Compound `<Root>` / `<Trigger>` / `<Content>` / `<Close>` / `<Title>` / `<Description>` for click-anchored non-modal disclosure.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/dialog/',
    status: 'preview',
  },
  {
    slug: 'component-toast',
    name: '@kumiki/components/toast',
    layer: 4,
    summary:
      'Compound `<Toaster>` / `<Viewport>` / `<Item>` / `<Title>` / `<Description>` / `<Close>` for transient notifications with auto-dismiss + hover-pause.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/alert/',
    status: 'preview',
  },
  {
    slug: 'component-menu',
    name: '@kumiki/components/menu',
    layer: 4,
    summary:
      'Compound `<Root>` / `<Trigger>` / `<Menu>` / `<Item>` / `<Separator>` for action menus. Single-level; submenus deferred.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/menubar/',
    status: 'preview',
  },

  // ── Layer 5 — Atelier (preview) ───────────────────────────────────────────
  {
    slug: 'atelier-toggle',
    name: '@kumiki/atelier/toggle',
    layer: 5,
    summary: 'Layer 5 preview — styled Toggle (Tailwind v4 + vanilla CSS variants).',
    live: true,
    status: 'preview',
  },
  {
    slug: 'atelier-dialog',
    name: '@kumiki/atelier/dialog',
    layer: 5,
    summary: 'Layer 5 preview — styled Dialog (Tailwind v4 + vanilla CSS variants).',
    live: true,
    status: 'preview',
  },
];

export function findPlayground(slug: string): PlaygroundEntry | undefined {
  return PLAYGROUNDS.find((p) => p.slug === slug);
}

export type LivePlaygroundLoader = () => Promise<{ default: Component }>;

/**
 * Lazy-loaded interactive demo components.
 * Add new packages here as they implement live demos.
 */
export const LIVE_PLAYGROUNDS: Record<string, LivePlaygroundLoader> = {
  'component-toggle': () => import('./demos/component-toggle.svelte'),
  'attachment-toggle': () => import('./demos/attachment-toggle.svelte'),
  'component-switch': () => import('./demos/component-switch.svelte'),
  'component-combobox': () => import('./demos/component-combobox.svelte'),
  'component-checkbox': () => import('./demos/component-checkbox.svelte'),
  'component-radio-group': () => import('./demos/component-radio-group.svelte'),
  'component-tabs': () => import('./demos/component-tabs.svelte'),
  'component-dialog': () => import('./demos/component-dialog.svelte'),
  'component-tooltip': () => import('./demos/component-tooltip.svelte'),
  'component-select': () => import('./demos/component-select.svelte'),
  'component-form-field': () => import('./demos/component-form-field.svelte'),
  'component-accordion': () => import('./demos/component-accordion.svelte'),
  'component-slider': () => import('./demos/component-slider.svelte'),
  'component-number-field': () => import('./demos/component-number-field.svelte'),
  'component-popover': () => import('./demos/component-popover.svelte'),
  'component-toast': () => import('./demos/component-toast.svelte'),
  'component-menu': () => import('./demos/component-menu.svelte'),
};
