/**
 * Registry of every Kumiki package available in the Playground.
 *
 * Generated by hand for now; future tooling can derive this from
 * `pnpm-workspace.yaml`. Each entry has:
 *   - `slug`: URL slug for `/play/<slug>`
 *   - `name`: full npm package name
 *   - `layer`: 0–5 (matches docs/design/02-architecture.md)
 *   - `summary`: one-line description
 *   - `live`: whether the package has a live, interactive demo (Layer 4/5 only)
 *   - `apgUrl`: matching APG pattern URL, if any
 *
 * The slug omits the `@kumiki/` prefix — `@kumiki/component-toggle` → `component-toggle`.
 */

import type { Component } from 'svelte';

export interface PlaygroundEntry {
  slug: string;
  name: string;
  layer: 0 | 1 | 2 | 3 | 4 | 5;
  summary: string;
  /** True when an interactive demo Svelte component is provided. */
  live: boolean;
  apgUrl?: string;
  /** Status hint for the UI badge. */
  status: 'unreleased' | 'preview' | 'stable';
}

export const PLAYGROUNDS: ReadonlyArray<PlaygroundEntry> = [
  // ── Shared / Layer 0–2 ───────────────────────────────────────────────────
  {
    slug: 'types',
    name: '@kumiki/types',
    layer: 0,
    summary: 'Shared TypeScript types — Snippet helpers, ARIA props, validation result types.',
    live: false,
    status: 'unreleased',
  },
  {
    slug: 'primitives',
    name: '@kumiki/primitives',
    layer: 1,
    summary:
      'Layer 1 framework-agnostic primitives — focus-trap, dismissable, id, locale, live-region, collection, interactions, motion, portal.',
    live: false,
    status: 'preview',
  },
  {
    slug: 'locale',
    name: '@kumiki/locale',
    layer: 1,
    summary: 'Per-language locale data, dynamically importable. Initial set: 10 languages.',
    live: false,
    status: 'unreleased',
  },
  {
    slug: 'runtime',
    name: '@kumiki/runtime',
    layer: 2,
    summary:
      'Minimal FSM runtime — pure TypeScript, framework-agnostic, with XState-compatible JSON export.',
    live: false,
    status: 'preview',
  },

  // ── Layer 2 — Machines ────────────────────────────────────────────────────
  {
    slug: 'machine-toggle',
    name: '@kumiki/machine-toggle',
    layer: 2,
    summary: 'Pure-TS FSM for the Toggle component.',
    live: false,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/button/',
    status: 'preview',
  },
  ...(
    [
      'switch',
      'checkbox',
      'radio-group',
      'tabs',
      'dialog',
      'tooltip',
      'combobox',
      'select',
      'form-field',
    ] as const
  ).map(
    (slug) =>
      ({
        slug: `machine-${slug}`,
        name: `@kumiki/machine-${slug}`,
        layer: 2,
        summary: `Pure-TS FSM for the ${slug} component.`,
        live: false,
        status: 'unreleased',
      }) satisfies PlaygroundEntry,
  ),

  // ── Layer 3 — Attachments ────────────────────────────────────────────────
  {
    slug: 'attachment-toggle',
    name: '@kumiki/attachment-toggle',
    layer: 3,
    summary: 'Svelte 5 attachment for Toggle. Drives ARIA + data-state directly on a DOM node.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/button/',
    status: 'preview',
  },
  ...(
    [
      'switch',
      'checkbox',
      'radio-group',
      'tabs',
      'dialog',
      'tooltip',
      'combobox',
      'select',
      'form-field',
    ] as const
  ).map(
    (slug) =>
      ({
        slug: `attachment-${slug}`,
        name: `@kumiki/attachment-${slug}`,
        layer: 3,
        summary: `Svelte 5 attachment for ${slug}.`,
        live: false,
        status: 'unreleased',
      }) satisfies PlaygroundEntry,
  ),

  // ── Layer 4 — Compound components ────────────────────────────────────────
  {
    slug: 'component-toggle',
    name: '@kumiki/component-toggle',
    layer: 4,
    summary:
      'Compound `<Toggle.Root>` button — controlled or uncontrolled, with `child` snippet support.',
    live: true,
    apgUrl: 'https://www.w3.org/WAI/ARIA/apg/patterns/button/',
    status: 'preview',
  },
  ...(
    [
      'switch',
      'checkbox',
      'radio-group',
      'tabs',
      'dialog',
      'tooltip',
      'combobox',
      'select',
      'form-field',
    ] as const
  ).map(
    (slug) =>
      ({
        slug: `component-${slug}`,
        name: `@kumiki/component-${slug}`,
        layer: 4,
        summary: `Compound Svelte 5 components (Root/Trigger/Item) for ${slug}.`,
        live: false,
        status: 'unreleased',
      }) satisfies PlaygroundEntry,
  ),

  // ── Layer 5 — Recipes (preview) ───────────────────────────────────────────
  {
    slug: 'recipes-toggle',
    name: '@kumiki/recipes-toggle',
    layer: 5,
    summary: 'Layer 5 preview — styled, copy-paste-friendly Toggle templates.',
    live: false,
    status: 'unreleased',
  },
  {
    slug: 'recipes-dialog',
    name: '@kumiki/recipes-dialog',
    layer: 5,
    summary: 'Layer 5 preview — styled, copy-paste-friendly Dialog templates.',
    live: false,
    status: 'unreleased',
  },
];

export function findPlayground(slug: string): PlaygroundEntry | undefined {
  return PLAYGROUNDS.find((p) => p.slug === slug);
}

export type LivePlaygroundLoader = () => Promise<{ default: Component }>;

/**
 * Lazy-loaded interactive demo components.
 * Add new packages here as they implement live demos.
 */
export const LIVE_PLAYGROUNDS: Record<string, LivePlaygroundLoader> = {
  'component-toggle': () => import('./demos/component-toggle.svelte'),
  'attachment-toggle': () => import('./demos/attachment-toggle.svelte'),
};
