/**
 * `@kumiki/machine-toast` — pure-TS FSM for the Toast (toaster queue).
 *
 * Models the toaster as an ordered queue of toast items. The machine is
 * queue + metadata only — per-toast auto-dismiss timers, hover-pause
 * arithmetic, and aria-live announcements live in the Layer 3 attachment.
 *
 * Each item carries presentation hints (`type`, `politeness`) and a
 * `duration` that the attachment uses to schedule a `REMOVE` after the
 * specified ms. `duration: -1` (or `Infinity`) marks a sticky toast
 * that only goes away on explicit `REMOVE` / `CLEAR`.
 *
 * @see https://www.w3.org/TR/wai-aria-practices-1.2/#live
 * @see https://www.w3.org/WAI/ARIA/apg/patterns/alert/
 */

import { defineMachine, type Machine } from '@kumiki/runtime';

export type ToastType = 'info' | 'success' | 'warning' | 'error';

/** ARIA-live politeness; mapped to `aria-live` on the toast wrapper. */
export type ToastPoliteness = 'polite' | 'assertive';

export interface ToastItem {
  /** Stable identifier — caller-supplied or generated by Layer 3. */
  id: string;
  title: string;
  description?: string;
  type?: ToastType;
  /** Auto-dismiss delay in ms. -1 (or Infinity) = sticky. Default 5000. */
  duration?: number;
  politeness?: ToastPoliteness;
  /** Free-form metadata — passed back to the consumer's render. */
  meta?: Record<string, unknown>;
}

export type ToastEvent =
  | { type: 'ADD'; toast: ToastItem }
  | { type: 'REMOVE'; id: string }
  | { type: 'UPDATE'; id: string; patch: Partial<Omit<ToastItem, 'id'>> }
  | { type: 'CLEAR' }
  | { type: 'SET.MAX'; value: number };

export interface ToastContext {
  toasts: readonly ToastItem[];
  /** Hard limit; older toasts dropped from the front when exceeded. */
  max: number;
  /** Default duration applied to ADDs that omit it. */
  defaultDuration: number;
}

export type ToastState = 'idle';

export type ToastMachine = Machine<ToastContext, ToastEvent, ToastState>;

export interface CreateToastInput {
  /** Default 5; oldest dropped when full. Use Infinity to disable trim. */
  max?: number;
  /** Default 5000ms. */
  defaultDuration?: number;
  /** Initial toasts — useful for SSR hydration. */
  initial?: ToastItem[];
}

function trim(list: readonly ToastItem[], max: number): ToastItem[] {
  if (!Number.isFinite(max) || list.length <= max) return [...list];
  return list.slice(list.length - max);
}

/**
 * Construct a fresh Toast (toaster) machine.
 *
 * @when-to-use Transient, non-modal feedback — "Saved", "Failed to send",
 *              "Update available". One toaster per app, mounted near the
 *              root.
 *
 * @anti-pattern Don't use Toast for anything the user has to act on
 *               (use Dialog). Don't use it for permanent status
 *               (use a banner). Don't put critical errors that need a
 *               response in a toast — they may be missed.
 *
 * @see https://www.w3.org/TR/wai-aria-practices-1.2/#live
 */
export function createToastMachine(input: CreateToastInput = {}): ToastMachine {
  const max = input.max ?? 5;
  const defaultDuration = input.defaultDuration ?? 5000;
  const initial = trim(input.initial ?? [], max);

  const factory = defineMachine<ToastContext, ToastEvent, ToastState>({
    id: 'toast',
    initial: 'idle',
    context: { toasts: initial, max, defaultDuration },
    states: {
      idle: {
        on: {
          ADD: {
            actions: [
              {
                type: 'add',
                exec: (ctx, e) => {
                  if (e.type !== 'ADD') return;
                  const incoming: ToastItem = {
                    duration: ctx.defaultDuration,
                    ...e.toast,
                  };
                  // Replace if id already present (idempotent re-ADD).
                  const without = ctx.toasts.filter((t) => t.id !== incoming.id);
                  return { toasts: trim([...without, incoming], ctx.max) };
                },
              },
            ],
          },
          REMOVE: {
            actions: [
              {
                type: 'remove',
                exec: (ctx, e) => {
                  if (e.type !== 'REMOVE') return;
                  const next = ctx.toasts.filter((t) => t.id !== e.id);
                  if (next.length === ctx.toasts.length) return;
                  return { toasts: next };
                },
              },
            ],
          },
          UPDATE: {
            actions: [
              {
                type: 'update',
                exec: (ctx, e) => {
                  if (e.type !== 'UPDATE') return;
                  let changed = false;
                  const next = ctx.toasts.map((t) => {
                    if (t.id !== e.id) return t;
                    changed = true;
                    return { ...t, ...e.patch, id: t.id };
                  });
                  if (!changed) return;
                  return { toasts: next };
                },
              },
            ],
          },
          CLEAR: {
            actions: [
              {
                type: 'clear',
                exec: (ctx) => {
                  if (ctx.toasts.length === 0) return;
                  return { toasts: [] };
                },
              },
            ],
          },
          'SET.MAX': {
            actions: [
              {
                type: 'setMax',
                exec: (ctx, e) => {
                  if (e.type !== 'SET.MAX') return;
                  return { max: e.value, toasts: trim(ctx.toasts, e.value) };
                },
              },
            ],
          },
        },
      },
    },
  });

  return factory();
}
